/**
 * @file dom.ts
 * @description
 * Platform‑specific DOM operations for the Nebula DOM renderer.
 *
 * These are the lowest‑level primitives Nebula Core relies on to:
 * - create nodes
 * - insert nodes
 * - remove nodes
 * - update text
 * - update props
 * - bind events
 *
 * Nebula does NOT use a virtual DOM or diffing. These operations are
 * called directly by fine‑grained reactive bindings generated by the
 * template compiler.
 */

/**
 * Create a DOM element node.
 *
 * @param type - The HTML tag name (e.g., "div", "span").
 * @returns The created HTMLElement.
 */
export function createElement(type: string): HTMLElement {
    return document.createElement(type);
}

/**
 * Create a DOM text node.
 *
 * @param value - Initial text content.
 * @returns The created Text node.
 */
export function createText(value: string): Text {
    return document.createTextNode(value);
}

/**
 * Create a DocumentFragment.
 *
 * Used for grouping children without introducing extra DOM elements.
 *
 * @returns A new DocumentFragment.
 */
export function createFragment(): DocumentFragment {
    return document.createDocumentFragment();
}

/**
 * Insert a child node into a parent before an optional anchor.
 *
 * @param parent - The parent DOM node.
 * @param child - The node to insert.
 * @param anchor - The node to insert before, or null to append.
 */
export function insert(parent: Node, child: Node, anchor: Node | null = null): void {
    parent.insertBefore(child, anchor);
}

/**
 * Remove a DOM node from its parent.
 *
 * @param node - The node to remove.
 */
export function remove(node: Node): void {
    const parent = node.parentNode;
    if (parent) parent.removeChild(node);
}

/**
 * Update the text content of a Text node.
 *
 * @param node - The Text node to update.
 * @param value - The new text content.
 */
export function setText(node: Text, value: string): void {
    node.data = value;
}

/**
 * Set or update a property on an HTMLElement.
 *
 * @param el - The element to update.
 * @param name - The property name.
 * @param value - The new value.
 */
export function setProp(el: HTMLElement, name: string, value: any): void {
    // Null/undefined removes the property
    if (value == null) {
        el.removeAttribute(name);
        return;
    }

    // Boolean props
    if (typeof value === "boolean") {
        if (value) el.setAttribute(name, "");
        else el.removeAttribute(name);
        return;
    }

    // Normal props
    el.setAttribute(name, String(value));
}

/**
 * Apply a style object to an HTMLElement.
 *
 * @param el - The element to update.
 * @param style - A map of CSS property → value.
 */
export function setStyle(el: HTMLElement, style: Record<string, string>): void {
    for (const key in style) {
        el.style[key as any] = style[key];
    }
}

/**
 * Set the class attribute on an element.
 *
 * @param el - The element to update.
 * @param className - The class string.
 */
export function setClass(el: HTMLElement, className: string): void {
    el.className = className;
}

/**
 * Add an event listener to an element.
 *
 * @param el - The element to bind to.
 * @param name - Event name (e.g., "click").
 * @param handler - The event handler function.
 */
export function addEvent(el: HTMLElement, name: string, handler: EventListener): void {
    el.addEventListener(name, handler);
}

/**
 * Remove an event listener from an element.
 *
 * @param el - The element to unbind from.
 * @param name - Event name.
 * @param handler - The handler to remove.
 */
export function removeEvent(el: HTMLElement, name: string, handler: EventListener): void {
    el.removeEventListener(name, handler);
}
